const express= require('express')
const MovieController=require('../controllers/movie.controller')
const { protectRoute } = require('../middleware/protectRoute')
const router=express.Router()
router.get("/trending",MovieController.getTrendingMovie)
router.get("/all",MovieController.getAll)
router.patch("/:id/view",protectRoute,MovieController.viewMovie)
router.patch("/:id/rate",protectRoute,MovieController.rateMovie)
router.delete("/:id/delete",MovieController.deleteMovie)
router.post("/create",MovieController.generateMovies)
router.post("/:id/favorite",protectRoute,MovieController.loveMovie)
router.get("/:id/details",MovieController.getMovieDetails)
router.get("/:category",MovieController.getMoviesByCategory)
module.exports=router