const express= require('express')
const SearchController=require('../controllers/search.controller')
const { protectRoute } = require('../middleware/protectRoute')
const router=express.Router()
router.get("/person",protectRoute,SearchController.searchPerson)
router.get("/movie",protectRoute,SearchController.searchMovie)
router.get("/productionCompany",protectRoute,SearchController.searchProductionCompany)
router.get("/tv/:query",SearchController.searchTv)
router.get('/history',SearchController.getSearchHistory)
router.delete('/history/:id',SearchController.removeItemFromSearchHistory)
module.exports=router